Modal
js-tasks-ru/htmlcss-20220919_andrewinapple pull request #12
Opened 2022-10-21 20:23 UTC by AndrewKapu

2022-10-21 20:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-21 20:37 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-10-23 17:42 UTC, GSemikozov requested changes

2022-10-23 17:42 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
кнопка у нас уже есть, ее здесь заново описывать не надо

2022-10-23 17:42 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    left: 50%;
растягиваем на весь экран, фон делаем полупрозрачным через rgba

2022-10-23 17:42 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__text-content {
а по середине будем размещать вот этот элемент

2022-10-23 17:42 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background-color: var(--text-bg-color);
точно ли такой фон? и переменная с таким именем больше говорит о том что фон будет для текста нежели для блока, в котором не только текст)

2022-10-23 17:42 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background-color: #fefefe;
а это видимо лишнее

2022-10-25 11:33 UTC, AndrewKapu commented on 05-lection3/02-modal/modal.css
> +.button {
А как тогда её использовать? У нас же нет PHP, например, чтобы использовать include.

2022-10-25 14:21 UTC, AndrewKapu commented on 05-lection3/02-modal/modal.css
> +    background-color: #fefefe;
Да, случайно продублировал, исправил)

2022-10-25 14:25 UTC, AndrewKapu commented on 05-lection3/02-modal/modal.css
> +    background-color: var(--text-bg-color);
Здесь не совсем понял, этот цвет именно для бэкграунда блока-обёртки текстовых элементов.

2022-10-25 14:25 UTC, AndrewKapu commented on 05-lection3/02-modal/modal.css
> +.modal__text-content {
Исправил.

2022-10-25 14:28 UTC, AndrewKapu commented on 05-lection3/02-modal/modal.css
> +    left: 50%;
Тут вопрос, - как правильно растянуть на весь экран, чтобы задизейблить всё остальное модалкой. Я пока только нашёл способ задания отрицательного z-index и добавления position: absolute кнопке. Но это, как мне кажется, неправильный способ.

2022-10-25 14:39 UTC, AndrewKapu commented on 05-lection3/02-modal/modal.css
> +    left: 50%;
Сделано. Задизейблил всю страницу при открытии модалки через position absolute + top: 0, left:0, right: 0, bottom: 0.

2022-10-25 14:41 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-26 20:06 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
глобальные стили (мы ведь компоненты подключаем в main.css) доступны, разметку копируем из файла где решение по кнопкам

2022-10-26 20:07 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background-color: var(--text-bg-color);
--text-bg-color - читается как "задай фон тексту"

2022-10-26 20:07 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background-color: var(--text-bg-color);
цвет совпадает с макетом?

2022-10-26 20:08 UTC, GSemikozov requested changes

2022-10-26 20:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.button {
так что - отсюда стили надо удалить

2022-10-26 20:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
fixed

2022-10-26 20:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    width: 100%;
width + height лишние, мы уже координатами разместили блок по границам вьюпорта

2022-10-26 20:08 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
а вот здесь уже absolute

2022-10-27 11:27 UTC, AndrewKapu commented on 05-lection3/02-modal/modal.css
> +.button {
Теперь понял, сделал.

2022-10-27 11:42 UTC, AndrewKapu commented on 05-lection3/02-modal/modal.css
> +    position: absolute;
Исправил

2022-10-27 11:42 UTC, AndrewKapu commented on 05-lection3/02-modal/modal.css
> +    position: fixed;
Исправил

2022-10-27 11:43 UTC, AndrewKapu commented on 05-lection3/02-modal/modal.css
> +    width: 100%;
Понял, исправил.

2022-10-27 11:45 UTC, AndrewKapu commented on 05-lection3/02-modal/modal.css
> +    background-color: var(--text-bg-color);
> цвет совпадает с макетом?

Да, насколько я вижу.

2022-10-28 20:12 UTC, GSemikozov approved these changes

2022-10-28 20:12 UTC, jsru commented
К сожалению, PR не может быть замержен, GSemikozov вероятно сможет помочь.

2022-10-28 20:14 UTC, GSemikozov approved these changes

2022-10-28 20:14 UTC, merged