Created layout
js-tasks-ru/htmlcss-20220919_andrewinapple pull request #5
Opened 2022-09-27 16:30 UTC by AndrewKapu

2022-09-27 16:30 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-27 20:35 UTC, GSemikozov requested changes

2022-09-27 20:35 UTC, GSemikozov commented on assets/css/global/global.css
> +.wrapper {
отсюда и ниже - это все-таки не какие-то глобальные стили, а конкретные компоненты, поэтому их следует оформить соответствующим образом

2022-09-28 19:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-09-29 08:04 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 09:40 UTC, AndrewKapu commented on assets/css/global/global.css
> +.wrapper {
Убрал данные стили из global.css и добавил их в бэм-блоки container, page и preview.

2022-09-29 20:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2022-09-29 21:11 UTC, GSemikozov approved these changes

2022-09-29 21:11 UTC, merged