Accordion
js-tasks-ru/htmlcss-20220919_andrewinapple pull request #6
Opened 2022-10-03 20:37 UTC by AndrewKapu

Created accordion element, no animation.

2022-10-03 20:37 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-05 06:36 UTC, GSemikozov requested changes

2022-10-05 06:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
импортируем в fonts.css )

2022-10-05 06:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
лишнее ограничение

2022-10-05 06:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
судя по структуре, это все-таки будет элемент блока - .accordion__item, c margin-bottom: 8px

2022-10-05 06:36 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] .accordion__title:after {
и еще при .accordion[open] меняется паддинг снизу

2022-10-05 06:36 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +    <details class="accordion">
а если будет 3 секции как в макете?

2022-10-05 08:58 UTC, AndrewKapu commented on 03-lection1/02-accordion/accordion.css
> +@import url('https://fonts.googleapis.com/css2?family=Inter&display=swap');
Вынес в отдельный файл fonts.css.

2022-10-05 09:00 UTC, AndrewKapu commented on 03-lection1/02-accordion/accordion.css
> +    width: 730px;
Переделал на max-width для адаптивности на меньших экранах.

2022-10-05 09:06 UTC, AndrewKapu commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
Не совсем согласен, тут для отступа снизу лучше, наверное, сделать микс <details class="accordion accordion__item">... </details> для отступа между аккордионами.

2022-10-05 11:13 UTC, AndrewKapu commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] .accordion__title:after {
Поменял отступ при открытом <details> у <summary> и <p>.

2022-10-05 11:17 UTC, AndrewKapu commented on 03-lection1/02-accordion/index.html
> +    <details class="accordion">
Тут нужно будет сделать микс для отступов между аккордионами.

2022-10-06 06:06 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
микс - это когда миксуем класс элемента одного блока с классом другого блока, который встраиваем в данный. В нашем случае accordion accordion__item - это не микс, а расположение классов блока и его элемента на одном уровне, что является ошибкой - элемент блока это всегда вложенный элемент, "ребенок родителя", который не может быть одновременно и ребенком, и своим родителем.
в общем - секции аккордиона - это вложенные элементы блока accordion

2022-10-06 06:06 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +    <details class="accordion">
см выше

2022-10-06 13:03 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-06 13:04 UTC, AndrewKapu commented on 03-lection1/02-accordion/accordion.css
> +.accordion {
Сделал обёртку для каждого аккордиона.

2022-10-06 20:17 UTC, GSemikozov requested changes

2022-10-06 20:17 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import 'fonts.css';
неа, их все равно не надо импортировать - мы ведь шрифты подключаем в main.css, а его - на странице, поэтому все стили из этого файла будут доступны

2022-10-06 20:17 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
здесь задаем padding: 24px 32px

2022-10-06 20:17 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-left: 32px;
а здесь уже не нужны никакие марджины

2022-10-06 20:17 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] .accordion__title:after {
при .accordion[open] - padding-bottom: 32px

2022-10-06 20:17 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +    margin-left: 32px;
вместо этих марджинов здесь нужен margin-top: 16px

2022-10-06 20:17 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +            <p class="accordion__el">
весь скрытый контект нужно завернуть в один общий класс - если это не accordion__el, тогда например accordion__content

2022-10-06 20:17 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +    <div class="accordion">
каждую секцию не надо заворачивать в accordion - иначе по-прежнему получается что у нас здесь 3 отдельных аккордиона, а не 3 секции у одного. Обертка с классом accordion заворачивает 3 секции с классом accordion__item

2022-10-07 20:59 UTC, AndrewKapu commented on 03-lection1/02-accordion/accordion.css
> +@import 'fonts.css';
Но ведь это отдельная задача в отдельной папке, поэтому и подключил шрифты здесь.

2022-10-07 21:13 UTC, AndrewKapu commented on 03-lection1/02-accordion/accordion.css
> +    margin-bottom: 8px;
Добавил.

2022-10-07 21:13 UTC, AndrewKapu commented on 03-lection1/02-accordion/accordion.css
> +    margin-left: 32px;
Убрал.

2022-10-07 21:14 UTC, AndrewKapu commented on 03-lection1/02-accordion/accordion.css
> +.accordion[open] .accordion__title:after {
Добавил.

2022-10-07 21:15 UTC, AndrewKapu commented on 03-lection1/02-accordion/accordion.css
> +    margin-left: 32px;
Добавил.

2022-10-07 21:20 UTC, AndrewKapu commented on 03-lection1/02-accordion/index.html
> +    <div class="accordion">
Исправил, спасибо.

2022-10-08 07:22 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-08 10:14 UTC, GSemikozov requested changes

2022-10-08 10:14 UTC, GSemikozov commented on 03-lection1/02-accordion/index.html
> +    <link rel="stylesheet" href="../../assets/css/main.css">
вот здесь подключается файл font.css с нужным нам шрифтом

2022-10-08 10:14 UTC, GSemikozov commented on 03-lection1/02-accordion/accordion.css
> +@import 'fonts.css';
повторюсь - глобальные стили на то и глобальные, что доступны на уровне любой страницы (см коммент ниже), нет необходимости дублировать их на уровне каждого компонента

2022-10-09 09:36 UTC, AndrewKapu commented on 03-lection1/02-accordion/index.html
> +    <link rel="stylesheet" href="../../assets/css/main.css">
Подключил fonts.css в index.html.

2022-10-09 09:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2022-10-10 08:40 UTC, GSemikozov approved these changes

2022-10-10 08:40 UTC, merged